### ISSUE TITLE
master does not build/run?

### ISSUE THREAD

**Issue by hffmnn** [CastilloSanRafael/castillo#2]
When checking out `master` and execute a `sbt run` in project root, I get this
```
[warn] No main class detected
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:run for the full output.
[error] (root/compile:run) No main class detected.
[error] Total time: 0 s, completed Feb 8, 2015 10:59:41 PM
```
I am on `sbt launcher version 0.13.7` and `Scala code runner version 2.11.5 -- Copyright 2002-2013, LAMP/EPFL`

Any ideas?

**Comment by atooni** [comment]
Hi, 

i think you are running into a known issue with Play / SBT (not sure which). The Play application lives in a subproject called server and for some reason sbt doesn't recognize the subproject. 

You have to run 'sbt' from the project root, then switch the project with 'project server', then you should be able to start the server with 'run'. 

Hope that helps 
Andreas

**Comment by hffmnn** [comment]
Thanks a lot, that did the trick. Guess this issue can be closed now!

Regards,
Christian

**Comment by atooni** [comment]
good to hear ....

have fun
