### ISSUE TITLE
update to 0.6.1 error

### ISSUE THREAD

**Issue by lshoo** [CastilloSanRafael/castillo#3]
Hi,
I'm a newbie for scalajs, Can you update the scalajs from 0.5.6 to 0.6.1? 
Thanks.
tiGer

**Comment by atooni** [comment]
Hi there, 

I wasn't working on the project for a couple of days as I am actually preparing for seminars :) and missed the upgrade to 0.6.1. I have now upgraded to Scala JS 0.6.1 and the corresponding libraries. 

Best regards & have fun 
Andreas

**Comment by lshoo** [comment]
Thanks
Best regards
tiGer
